//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflow.Data {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inflow.Data.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comparison type {0} is not implemented..
        /// </summary>
        public static string ComparisonTypeNotImpemented {
            get {
                return ResourceManager.GetString("ComparisonTypeNotImpemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditional operator {0} is not implemented..
        /// </summary>
        public static string ConditionalOperatorNotImplemented {
            get {
                return ResourceManager.GetString("ConditionalOperatorNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join type between tables {0} is not implemented..
        /// </summary>
        public static string JoinTypeNotImplemented {
            get {
                return ResourceManager.GetString("JoinTypeNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order mode {0} is not implemented..
        /// </summary>
        public static string OrderModeNotImplemented {
            get {
                return ResourceManager.GetString("OrderModeNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  See more in logs..
        /// </summary>
        public static string SeeMoreInLogs {
            get {
                return ResourceManager.GetString("SeeMoreInLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql compiler {0} not implemented..
        /// </summary>
        public static string SqlCompilerNotImplemented {
            get {
                return ResourceManager.GetString("SqlCompilerNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql connection for sql-compiler {0} not implemented..
        /// </summary>
        public static string SqlConnectionForThisSqlCompilerNotImplemented {
            get {
                return ResourceManager.GetString("SqlConnectionForThisSqlCompilerNotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured while sending request to database..
        /// </summary>
        public static string SqlErrorMessage {
            get {
                return ResourceManager.GetString("SqlErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
    }
}
