//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inflow.Core.Data {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Inflow.Core.Data.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string ComparisonTypeNotImpemented {
            get {
                return ResourceManager.GetString("ComparisonTypeNotImpemented", resourceCulture);
            }
        }
        
        public static string ConditionalOperatorNotImplemented {
            get {
                return ResourceManager.GetString("ConditionalOperatorNotImplemented", resourceCulture);
            }
        }
        
        public static string JoinTypeNotImplemented {
            get {
                return ResourceManager.GetString("JoinTypeNotImplemented", resourceCulture);
            }
        }
        
        public static string OrderModeNotImplemented {
            get {
                return ResourceManager.GetString("OrderModeNotImplemented", resourceCulture);
            }
        }
        
        public static string SeeMoreInLogs {
            get {
                return ResourceManager.GetString("SeeMoreInLogs", resourceCulture);
            }
        }
        
        public static string SqlCompilerNotImplemented {
            get {
                return ResourceManager.GetString("SqlCompilerNotImplemented", resourceCulture);
            }
        }
        
        public static string SqlConnectionForThisSqlCompilerNotImplemented {
            get {
                return ResourceManager.GetString("SqlConnectionForThisSqlCompilerNotImplemented", resourceCulture);
            }
        }
        
        public static string SqlErrorMessage {
            get {
                return ResourceManager.GetString("SqlErrorMessage", resourceCulture);
            }
        }
        
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        public static string SqlOptionsAreNotImplemented {
            get {
                return ResourceManager.GetString("SqlOptionsAreNotImplemented", resourceCulture);
            }
        }
    }
}
